Repository BangCrush/BankAI-Frontend, pull requests merged in 2024-05, with the labels that each got.

#3 [remove] Storybook Example 삭제
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Configure.mdx
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: ♻️ refactor

#6 [feat] 상품 컴포넌트
  src/stories/molecules/product/index.js
  src/stories/molecules/product/index.stories.jsx
  src/stories/organisms/productList/index.js
  src/stories/organisms/productList/index.stories.jsx
  tailwind.config.js
Labels: 🎨ui

#10 [feat] 검색 창
  package-lock.json
  package.json
  src/stories/atoms/input/index.js
  src/stories/molecules/searchBar/index.js
  src/stories/molecules/searchBar/index.stories.jsx
  tailwind.config.js
Labels: 🎨ui

#13 [feat] 절대 경로 설정
  jsconfig.json
  package-lock.json
  package.json
  src/libs/store.js
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/atoms/accountItem/index.stories.jsx
  src/stories/atoms/input/index.stories.jsx
  src/stories/atoms/longButton/index.stories.jsx
  src/stories/atoms/mainCarousel/index.stories.jsx
  src/stories/atoms/mediumButton/index.stories.jsx
  src/stories/atoms/shortButton/index.stories.jsx
  src/stories/molecules/product/index.stories.jsx
  src/stories/molecules/searchBar/index.stories.jsx
  src/stories/organisms/productList/index.stories.jsx
Labels: ✨feat

#14 [feat] 계좌 히스토리 요소 컴포넌트, 미디움버튼 미세 조정, 캐러셀, 계좌 목록 요소 디렉토리 변경
  package-lock.json
  package.json
  src/stories/atoms/mediumButton/index.js
  src/stories/molecules/accHistory/index.js
  src/stories/molecules/accHistory/index.stories.jsx
  src/stories/molecules/accountItem/index.js
  src/stories/molecules/accountItem/index.stories.jsx
  src/stories/molecules/mainCarousel/index.js
  src/stories/molecules/mainCarousel/index.stories.jsx
Labels: ♻️ refactor, 🎨ui

#16 [fix] craco로 인한 오류사항 변경
  package.json
Labels: 🐛bug, ♻️ refactor

#18 [feat] node modules 의존성 충돌 문제 해결
  package-lock.json
  package.json
  src/index.js
Labels: 🐛bug

#19 [feat] 상품 종류 버튼
  src/stories/molecules/accHistory/index.js
  src/stories/molecules/accHistory/index.stories.jsx
  src/stories/molecules/accountItem/index.js
  src/stories/molecules/accountItem/index.stories.jsx
  src/stories/molecules/mainCarousel/index.js
  src/stories/molecules/mainCarousel/index.stories.jsx
  src/stories/molecules/prodButtons/index.js
  src/stories/molecules/prodButtons/index.stories.jsx
Labels: ♻️ refactor, 🎨ui

#24 [design] 메뉴 컴포넌트
  .storybook/main.js
  public/assets/menu1.svg
  public/assets/menu2.svg
  public/assets/menu3.svg
  public/assets/menu4.svg
  public/assets/menu5.svg
  src/constants/Icons.js
  src/stories/atoms/prodItem/index.js
  src/stories/atoms/prodItem/index.stories.jsx
  src/stories/molecules/mainCarousel/index.js
  src/stories/molecules/totalAcc/index.js
  src/stories/molecules/totalAcc/index.stories.js
  src/stories/organisms/prodContainer/index.js
  src/stories/organisms/prodContainer/index.stories.jsx
  tailwind.config.js
Labels: 🎨ui

#29 [feat] 마이페이지 및 상단바
  src/stories/molecules/headerBar/index.js
  src/stories/molecules/headerBar/index.stories.jsx
  src/stories/page/myPage/index.js
  src/stories/page/myPage/index.stories.jsx
Labels: 🎨ui

#27 [design] popularProd 컴포넌트
  public/assets/popular1.svg
  src/App.js
  src/routes/mainLayoutRouter.js
  src/stories/molecules/prodButtons/index.js
  src/stories/molecules/searchBar/index.js
  src/stories/organisms/popularProd/index.js
  src/stories/organisms/popularProd/index.stories.jsx
  src/stories/pages/product/ProductPage.jsx
  src/stories/templates/MainLayout.js
Labels: 🎨ui

#34 [design] 로그인 페이지
  src/App.js
  src/routes/mainLayoutRouter.js
  src/routes/subLayoutRouter.js
  src/stories/atoms/input/index.js
  src/stories/atoms/longButton/index.js
  src/stories/pages/loginPage/index.js
  src/stories/pages/myPage/index.js
  src/stories/pages/myPage/index.stories.jsx
  src/stories/pages/productPage/index.jsx
  src/stories/templates/SubLayout.js
Labels: 🎨ui

#40 [design] medium input 컴포넌트, 경고 컴포넌트
  src/stories/molecules/mediumInput/index.js
  src/stories/molecules/mediumInput/index.stories.jsx
  src/stories/molecules/warning/index.js
  src/stories/molecules/warning/index.stories.jsx
Labels: 🎨ui

#58 [fix] use-immer 모듈 버그 해결
  package-lock.json
  package.json
  src/stories/pages/IdentifyPage/index.jsx
Labels: 🐛bug

#55 [design] 캐러셀 Left / Right Arrow 수정
  src/stories/molecules/mainCarousel/index.js
Labels: ♻️ refactor, 🎨ui

#59 [fix] > 문자 오류 &gt로 수정
  src/stories/pages/mainPage/index.jsx
Labels: ♻️ refactor

#60 [feat] 회원가입 유효성 체크
  src/hooks/useValid.js
  src/routes/subLayoutRouter.js
  src/stories/atoms/input/index.js
  src/stories/atoms/input/index.stories.jsx
  src/stories/pages/joinPage/index.jsx
  src/stories/pages/joinPage/page1.jsx
  tailwind.config.js
Labels: ✨feat

#65 [feat] 회원가입 마지막 단계
  src/stories/pages/joinPage/index.jsx
  src/stories/pages/joinPage/page3.jsx
Labels: ✨feat, 🎨ui

#67 [feat] 대출가입 페이지 - 1단계, 2단계
  src/routes/noLayoutRouter.js
  src/routes/subLayoutRouter.js
  src/stories/atoms/title/index.js
  src/stories/molecules/headerBar/index.js
  src/stories/pages/loanPage/index.jsx
  src/stories/pages/loanPage/page1.jsx
  src/stories/pages/loanPage/page2.jsx
Labels: ✨feat, 🎨ui

#69 [design] 대출 신청 확인 페이지 구현
  src/stories/molecules/loanInfo/index.js
  src/stories/molecules/loanInfo/index.stories.jsx
  src/stories/organisms/bottomSheet/index.stories.jsx
  src/stories/pages/loanCheckPage/index.js
  src/stories/pages/loanCheckPage/index.stories.jsx
Labels: 🎨ui

#72 [feat] (대출) 매월 상환 금액 명시
  src/stories/pages/loanPage/page2.jsx
Labels: ✨feat

#82 [feat] 자동 납부일 페이지, custom selectBox
  src/stories/atoms/selectBox/index.js
  src/stories/atoms/selectBox/index.stories.jsx
  src/stories/pages/loanPage/index.jsx
  src/stories/pages/loanPage/page3.jsx
Labels: ✨feat, 🎨ui

#79 [design] 계좌이체 Warning 페이지 구현
  src/stories/organisms/bottomSheet/index.js
  src/stories/organisms/bottomSheet/index.stories.jsx
  src/stories/pages/bottomPages/loanCheckPage/index.js
  src/stories/pages/bottomPages/loanCheckPage/index.stories.jsx
  src/stories/pages/bottomPages/transferCheckPage/index.js
  src/stories/pages/bottomPages/transferCheckPage/index.stories.jsx
  src/stories/pages/bottomPages/transferWarningPage/index.js
  src/stories/pages/bottomPages/transferWarningPage/index.stories.jsx
Labels: 🎨ui

#84 [feat] 대출 상환방식에 따른 납부금액 계산
  src/constants/products.js
  src/stories/pages/loanPage/index.jsx
  src/stories/pages/loanPage/page2.jsx
Labels: ✨feat

#87 [design] 상환방식 설명 토글 컴포넌트
  src/constants/products.js
  src/stories/atoms/repayDesc/index.js
  src/stories/atoms/repayDesc/index.stories.jsx
  src/stories/pages/loanPage/index.jsx
  src/stories/pages/loanPage/page2.jsx
Labels: ✨feat, 🎨ui

#92 [fix] 로그인 버튼 fixed -> absolute
  src/stories/pages/IdentifyPage/page1.jsx
  src/stories/pages/IdentifyPage/page2.jsx
  src/stories/pages/IdentifyPage/page3.jsx
  src/stories/pages/joinPage/page1.jsx
  src/stories/pages/joinPage/page2.jsx
  src/stories/pages/joinPage/page3.jsx
  src/stories/pages/loanPage/page1.jsx
  src/stories/pages/loanPage/page2.jsx
  src/stories/pages/loanPage/page3.jsx
  src/stories/pages/loginPage/index.js
  src/stories/pages/prodDetail/index.js
  src/stories/pages/prodDetail/index.stories.jsx
  src/stories/pages/transferPage/page1.js
  src/stories/pages/transferPage/page2.js
  src/stories/templates/MainLayout.js
  src/stories/templates/SubLayout.js
Labels: 🐛bug

#93 [feat] 대출 상품 상세 페이지 라우팅 및 대출 가입 페이지로 연결
  src/routes/noLayoutRouter.js
  src/stories/organisms/prodBenefit/index.js
  src/stories/pages/prodDetail/index.js
  src/stories/pages/prodDetail/index.stories.jsx
Labels: ✨feat

#96 [design] 적금가입 페이지
  src/mocks/mockData.js
  src/routes/subLayoutRouter.js
  src/stories/molecules/mediumInput/index.js
  src/stories/molecules/mediumInput/index.stories.jsx
  src/stories/pages/savingsPage/index.jsx
Labels: 🎨ui

#102 [feat] 자동이체일 선택 페이지
  src/stories/atoms/selectBox/index.js
  src/stories/pages/loanPage/page3.jsx
  src/stories/pages/savingsPage/index.jsx
  src/stories/pages/savingsPage/page3.jsx
Labels: ✨feat, 🎨ui

#95 [feat] 계좌이체 페이지 관련
  public/assets/inoutacc1.svg
  src/stories/molecules/transferInfo/index.js
  src/stories/molecules/transferInfo/index.stories.jsx
  src/stories/organisms/prodBenefit/index.stories.jsx
  src/stories/organisms/prodBenefit2/index.js
  src/stories/organisms/prodBenefit2/index.stories.jsx
  src/stories/pages/bottomPages/transferCheckPage/index.js
  src/stories/pages/transferPage/index.js
  src/stories/pages/transferPage/page1.js
  src/stories/pages/transferPage/page2.js
  src/stories/pages/transferPage/page3.js
Labels: ♻️ refactor, ✨feat, 🎨ui

#105 [design] 자동이체 한도 안내 메세지
  src/stories/pages/savingsPage/index.jsx
  src/stories/pages/savingsPage/page3.jsx
Labels: 🎨ui

#108 [design] 대출 신용도 확인 페이지 - 직업명
  src/stories/atoms/selectBox/index.js
  src/stories/pages/loanPage/index.jsx
  src/stories/pages/loanPage/page3.jsx
  src/stories/pages/loanPage/page4.jsx
  src/stories/pages/loanPage/page5.jsx
  src/stories/pages/loanPage/page6.jsx
  src/stories/pages/savingsPage/page3.jsx
Labels: 🎨ui
