Repository BangCrush/BankAI-Frontend, pull requests merged in 2024-06, with the labels that each got.

#111 [fix] relative 옵션 삭제를 통한 계좌이체 페이지 Layout 개선
  src/stories/pages/transferPage/page1.js
  src/stories/pages/transferPage/page2.js
Labels: 🐛bug, 🎨ui

#113 [feat] 로그인, 회원가입 페이지 연결
  src/stories/pages/joinPage/page3.jsx
  src/stories/pages/loginPage/index.js
Labels: ✨feat

#115 [feat] 아이디 중복체크 api 통신
  package-lock.json
  package.json
  src/App.js
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/libs/axios.js
  src/stories/pages/joinPage/page3.jsx
Labels: 👽️ api, ✨feat

#118 [feat] 이메일 전송 api
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/stories/pages/joinPage/page1.jsx
  src/stories/pages/joinPage/page3.jsx
Labels: 👽️ api, ✨feat

#119 [feat] 이메일 중복체크
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/stories/atoms/input/index.js
  src/stories/atoms/shortButton/index.js
  src/stories/pages/joinPage/page1.jsx
Labels: 👽️ api, ✨feat

#121 [feat] 메일 코드 인증 확인
  src/stories/pages/joinPage/page1.jsx
Labels: 👽️ api, ✨feat

#124 [feat] 우편번호 자동 로딩
  src/stories/pages/joinPage/page2.jsx
  src/stories/pages/zipcodePage/index.jsx
Labels: ✨feat

#126 [feat] 회원가입 서버통신
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/hooks/useValid.js
  src/stories/pages/joinPage/index.jsx
  src/stories/pages/joinPage/page1.jsx
  src/stories/pages/joinPage/page2.jsx
  src/stories/pages/joinPage/page3.jsx
Labels: 👽️ api, ✨feat

#128 [design] ui 디자인 수정
  src/routes/noLayoutRouter.js
  src/stories/molecules/mainCarousel/index.js
  src/stories/molecules/totalAcc/index.js
  src/stories/pages/mainPage/index.jsx
Labels: 🎨ui

#129 [feat] 전체 상품 조회 api 통신
  src/api/productApi.js
  src/constants/products.js
  src/hooks/queries/productQueries.js
  src/stories/organisms/productList/index.js
  src/stories/pages/productPage/index.jsx
Labels: 👽️ api, ✨feat

#131 [fix] 회원가입 요청 실패 오류 해결
  src/api/userApi.js
  src/stories/pages/joinPage/page1.jsx
  src/stories/pages/joinPage/page3.jsx
Labels: 🐛bug

#133 [feat] 상품 상세 조회 api 통신
  src/api/productApi.js
  src/hooks/queries/productQueries.js
  src/routes/noLayoutRouter.js
  src/stories/molecules/prodDetailItem/index.js
  src/stories/organisms/productList/index.js
  src/stories/pages/prodDetail/index.js
  src/stories/pages/productPage/index.jsx
Labels: 👽️ api, ✨feat

#135 [feat] 로그인시 아이디가 존재하지 않을 경우
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/stories/pages/joinPage/page3.jsx
  src/stories/pages/loginPage/index.js
  src/stories/pages/loginPage/index.jsx
Labels: 👽️ api, ✨feat

#137 [feat] 로그인 성공/실패 case 처리
  src/hooks/queries/userQueries.js
  src/stories/pages/loginPage/index.jsx
Labels: 🐛bug, ✨feat

#141 [feat] 내 정보 api 통신
  public/assets/menu3.svg
  public/assets/menu4.svg
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/routes/subLayoutRouter.js
  src/stories/atoms/prodItem/index.js
  src/stories/organisms/prodContainer/index.js
  src/stories/pages/mainPage/index.jsx
  src/stories/pages/myPage/index.js
Labels: 👽️ api, ✨feat

#142 [feat] 내 계좌 목록 조회 api 통신
  src/api/accountApi.js
  src/hooks/queries/accountQueries.js
  src/stories/molecules/mainCarousel/index.js
  src/stories/molecules/mainCarousel/index.stories.jsx
  src/stories/pages/mainPage/index.jsx
Labels: 👽️ api, ✨feat

#143 [feat] 총 자산합계 조회 api 통신
  src/api/accountApi.js
  src/hooks/queries/accountQueries.js
  src/routes/noLayoutRouter.js
  src/stories/molecules/totalAcc/index.js
  src/stories/pages/loginPage/index.jsx
  src/stories/pages/mainPage/index.jsx
Labels: 👽️ api, ✨feat

#144 [feat] 사용자 로그인 api 통신
  package-lock.json
  package.json
  src/App.js
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/stories/organisms/productList/index.js
  src/stories/pages/loginPage/index.jsx
  src/stories/pages/mainPage/index.jsx
  src/stories/pages/myPage/index.js
  src/stories/pages/productPage/index.jsx
Labels: 👽️ api, ✨feat

#146 [feat] 로그인 유무에 따른 api 인가 방식 변경
  src/App.js
  src/api/accountApi.js
  src/api/userApi.js
  src/hooks/queries/userQueries.js
Labels: 👽️ api, ✨feat

#148 [fix] 자잘한 경고문, key 값 설정
  src/api/userApi.js
  src/stories/molecules/mainCarousel/index.js
  src/stories/organisms/prodContainer/index.js
  src/stories/pages/mainPage/index.jsx
  src/stories/pages/myPage/index.js
  src/stories/pages/productPage/index.jsx
Labels: 🐛bug, ♻️ refactor

#150 [feat] 전체 계좌 리스트 페이지, api 통신
  src/hooks/queries/accountQueries.js
  src/routes/noLayoutRouter.js
  src/stories/molecules/accountItem/index.js
  src/stories/pages/accountPage/index.jsx
  src/stories/pages/mainPage/index.jsx
Labels: 👽️ api, ✨feat, 🎨ui

#153 [feat] 계좌 잔액, 계좌 거래 내역 조회 api 통신, 계좌 거래내역 페이지 완성
  src/api/accountApi.js
  src/constants/accounts.js
  src/hooks/queries/accountQueries.js
  src/routes/noLayoutRouter.js
  src/stories/molecules/accHistory/index.js
  src/stories/molecules/accountItem/index.js
  src/stories/molecules/blueHeaderBar/index.js
  src/stories/pages/accHistoryPage/index.js
  src/stories/pages/accHistoryPage/index.jsx
  src/stories/pages/accountPage/index.jsx
  src/stories/pages/mainPage/index.jsx
  tailwind.config.js
Labels: 👽️ api, ✨feat, 🎨ui

#155 [feat] 가입 상품에 따른 상세 컴포넌트 변경
  public/assets/loan1.svg
  src/stories/organisms/prodBenefit2/index.js
  src/stories/organisms/prodBenefit3/index.js
  src/stories/organisms/prodBenefit3/index.stories.jsx
  src/stories/pages/prodDetail/index.jsx
Labels: ✨feat, 🎨ui

#157 [feat] 휴대폰 인증번호 발송
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/stories/atoms/shortButton/index.js
  src/stories/pages/IdentifyPage/index.jsx
  src/stories/pages/IdentifyPage/page1.jsx
  src/stories/pages/IdentifyPage/page2.jsx
  src/stories/pages/IdentifyPage/page3.jsx
Labels: 👽️ api, ✨feat

#159 [feat] 문자 본인인증 확인 api 통신
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/stories/pages/IdentifyPage/page3.jsx
Labels: 👽️ api, ✨feat

#162 [fix] 휴대폰 인증코드 불일치 버그 수정
  src/hooks/queries/userQueries.js
  src/stories/pages/IdentifyPage/page3.jsx
Labels: 🐛bug

#163 [feat] 본인인증에 이용한 사용자 정보 자동로딩
  src/stories/atoms/inherentInput/index.js
  src/stories/pages/IdentifyPage/index.jsx
  src/stories/pages/IdentifyPage/page1.jsx
  src/stories/pages/IdentifyPage/page2.jsx
  src/stories/pages/joinPage/index.jsx
  src/stories/pages/joinPage/page1.jsx
  src/stories/pages/loginPage/index.jsx
Labels: ✨feat

#167 [feat] 적금 상품의 최소 가입 금액 받아 입력값 유효성 체크
  src/App.js
  src/hooks/queries/userQueries.js
  src/stories/pages/prodDetail/index.jsx
  src/stories/pages/savingsPage/index.jsx
  src/stories/pages/savingsPage/page1.jsx
Labels: ✨feat

#169 [feat] 내 계좌 목록 조회 및 선택
  src/stories/atoms/accSelectBox/index.js
  src/stories/molecules/mediumInput/index.js
  src/stories/pages/savingsPage/page1.jsx
  src/stories/pages/savingsPage/page2.jsx
Labels: ✨feat

#173 [feat] 적금 상품 자동이체일, 최초 저축 금액 설정
  src/stories/atoms/accSelectBox/index.js
  src/stories/pages/savingsPage/index.jsx
  src/stories/pages/savingsPage/page1.jsx
  src/stories/pages/savingsPage/page2.jsx
  src/stories/pages/savingsPage/page3.jsx
  src/stories/pages/savingsPage/page4.jsx
Labels: ✨feat

#175 [feat] mainPage Product 이체하기 버튼 Action 추가
  public/index.html
  src/routes/noLayoutRouter.js
  src/stories/atoms/mediumButton/index.js
  src/stories/molecules/mainCarousel/index.js
  src/stories/pages/mainPage/index.jsx
  src/stories/pages/pwdPage/index.js
  src/stories/pages/pwdPage/index.stories.jsx
Labels: ♻️ refactor, ✨feat, 🎨ui, ➕ ADD

#177 [feat] 대출 신용도 확인 - 직장 api 통신
  src/api/userApi.js
  src/constants/products.js
  src/hooks/queries/userQueries.js
  src/stories/pages/IdentifyPage/page2.jsx
  src/stories/pages/loanPage/index.jsx
  src/stories/pages/loanPage/page2.jsx
  src/stories/pages/loanPage/page3.jsx
  src/stories/pages/savingsPage/index.jsx
Labels: 👽️ api, ✨feat, 🎨ui

#179 [feat] 계좌 비밀번호 입력, 재입력 팝업창 플로우
  src/stories/pages/pwdPage/index.js
  src/stories/pages/pwdPage/index.stories.jsx
  src/stories/pages/savingsPage/page4.jsx
Labels: ✨feat

#182 [feat] 적금 상품 api 통신
  src/api/accountApi.js
  src/constants/products.js
  src/hooks/queries/accountQueries.js
  src/stories/molecules/mainCarousel/index.js
  src/stories/pages/pwdPage/index.js
  src/stories/pages/savingsPage/page4.jsx
Labels: 👽️ api, ✨feat

#188 [fix] 예적금 가입 시 예상 혜택 문구 수정
  src/stories/organisms/prodBenefit/index.js
Labels: ♻️ refactor, 🎨ui

#189 [feat] 예금 가입 api 통신, 이체한도 초과 시 에러 핸들링
  src/constants/products.js
  src/hooks/queries/accountQueries.js
  src/routes/subLayoutRouter.js
  src/stories/pages/depositPage/index.jsx
  src/stories/pages/depositPage/page1.jsx
  src/stories/pages/depositPage/page2.jsx
  src/stories/pages/savingsPage/page3.jsx
  src/stories/pages/savingsPage/page4.jsx
Labels: 👽️ api, ✨feat

#192 [feat] 대출 플로우 및 api 통신
  src/stories/pages/loanPage/index.jsx
  src/stories/pages/loanPage/page4.jsx
  src/stories/pages/loanPage/page5.jsx
  src/stories/pages/loanPage/page6.jsx
Labels: 👽️ api, ✨feat

#199 [fix] mainCarousel 좌우 컨트롤러 표시 이슈 해결
  src/stories/molecules/mainCarousel/index.js
Labels: ♻️ refactor, 🎨ui

#203 [feat] 상품 메인 페이지 및 상품 타입별 페이지 이동
  public/assets/menu5.svg
  src/constants/Icons.js
  src/hooks/queries/productQueries.js
  src/routes/mainLayoutRouter.js
  src/routes/noLayoutRouter.js
  src/stories/atoms/prodItem/index.js
  src/stories/molecules/mainCarousel/index.js
  src/stories/molecules/searchBar/index.js
  src/stories/organisms/popularProd/index.js
  src/stories/organisms/prodContainer/index.js
  src/stories/pages/mainPage/index.jsx
  src/stories/pages/prodDetailPage/index.jsx
  src/stories/pages/prodDetailPage/index.stories.jsx
  src/stories/pages/productMainPage/index.jsx
  src/stories/pages/productPage/index.jsx
Labels: 👽️ api, ✨feat

#208 [feat] 상품 top3 조회 api 통신
  public/assets/fist.png
  public/assets/heart.png
  public/assets/shuttle.png
  src/api/productApi.js
  src/hooks/queries/productQueries.js
  src/stories/organisms/popularProd/index.js
  src/stories/pages/productMainPage/index.jsx
  src/stories/pages/productPage/index.jsx
Labels: 👽️ api, ✨feat

#220 [fix] 데이터 로딩 이전 렌더링 시도 이슈
  src/stories/atoms/prodItem/index.js
  src/stories/organisms/prodContainer/index.js
  src/stories/organisms/productList/index.js
  src/stories/pages/mainPage/index.jsx
  src/stories/pages/productPage/index.jsx
Labels: 🐛bug

#221 [feat] 인기상품 캐러셀 클릭 시 해당상품의 상세페이지 이동
  src/stories/organisms/popularProd/index.js
Labels: ✨feat

#222 [fix] 입출금 상품의 경우 가입기간 제한없음
  src/stories/molecules/product/index.js
Labels: ✨feat

#228 [fix] 토큰 재발급 버그 수정
  src/api/userApi.js
  src/hooks/queries/userQueries.js
  src/stories/organisms/prodContainer/index.js
Labels: 🐛bug

#232 [fix] 계좌 거래내역 조회 백 버튼 안먹음
  src/api/userApi.js
  src/stories/molecules/blueHeaderBar/index.js
Labels: 🐛bug

#234 [fix] 적금가입 및 상품 메인 헤더 바
  src/routes/noLayoutRouter.js
  src/routes/subLayoutRouter.js
  src/stories/pages/accountPage/index.jsx
  src/stories/pages/loanPage/page6.jsx
  src/stories/pages/productMainPage/index.jsx
  src/stories/pages/savingsPage/page4.jsx
  src/stories/pages/transferPage/page2.js
Labels: 🐛bug

#237 [feat] 음성 인식 서비스 버튼 구현
  .gitignore
  package-lock.json
  package.json
  server/index.js
  src/routes/noLayoutRouter.js
  src/stories/pages/audioRecordPage/index.jsx
  src/stories/pages/audioRecordPage/index.stories.jsx
  src/utils/token_util.js
Labels: ✨feat

#240 [feat] 자동이체 송금 계좌 AI 음성인식 자동 입력
  package-lock.json
  src/stories/pages/audioRecordPage/index.jsx
  src/stories/pages/savingsPage/page3.jsx
  src/stories/pages/transferPage/index.js
  src/stories/pages/transferPage/page1.js
Labels: 👽️ api, ✨feat

#243 [add] 응답 캐릭터 ai 영상 업로드
  public/assets/avatar/계좌비밀번4자리를말씀해주세요.mov
  public/assets/avatar/계좌비밀번호를다시한번입력해주세요.mov
  public/assets/avatar/계좌비밀번호숫4자리를설정해주세요.mov
  public/assets/avatar/계좌생성이완료되었습니다.mov
  public/assets/avatar/계좌이체를취소합니 .mov
  public/assets/avatar/다음화면으로이동합니.mov
  public/assets/avatar/상품가입을진행합니다.mov
  public/assets/avatar/상품가입페이지로이동합니다.mov
  public/assets/avatar/상품가입화면으로이동합니다.mov
  public/assets/avatar/상품상세페이지로이동합니다.mov
  public/assets/avatar/상품페이지로이동합니다.mov
  public/assets/avatar/어떤계좌로돈을보낼까요.mov
  public/assets/avatar/어떤상품을찾으시나요.mov
  public/assets/avatar/얼마를보낼까요.mov
  public/assets/avatar/얼마를저축할까요최소납입금액3만원입니다.mov
  public/assets/avatar/이체하시겠습니까.mov
  public/assets/avatar/이체화면으로이동합니다.mov
  public/assets/avatar/입력하신계좌번호가맞습니까.mov
  public/assets/avatar/입력하신금액이맞습니까.mov
  public/assets/avatar/출금하실계좌를선택해주세요.mov
Labels: ✨feat

#252 [feat] 이체 금액 AI 음성인식
  public/assets/avatar/계좌비밀번4자리를말씀해주세요.mov
  public/assets/avatar/계좌비밀번호를다시한번입력해주세요.mov
  public/assets/avatar/계좌비밀번호숫4자리를설정해주세요.mov
  public/assets/avatar/계좌생성이완료되었습니다.mov
  public/assets/avatar/계좌이체를취소합니 .mov
  public/assets/avatar/다음화면으로이동합니.mov
  public/assets/avatar/상품가입을진행합니다.mov
  public/assets/avatar/상품가입페이지로이동합니다.mov
  public/assets/avatar/상품가입화면으로이동합니다.mov
  public/assets/avatar/상품상세페이지로이동합니다.mov
  public/assets/avatar/상품페이지로이동합니다.mov
  public/assets/avatar/어떤계좌로돈을보낼까요.mov
  public/assets/avatar/어떤상품을찾으시나요.mov
  public/assets/avatar/얼마를보낼까요.mov
  public/assets/avatar/얼마를저축할까요최소납입금액3만원입니다.mov
  public/assets/avatar/이체하시겠습니까.mov
  public/assets/avatar/이체화면으로이동합니다.mov
  public/assets/avatar/입력하신계좌번호가맞습니까.mov
  public/assets/avatar/입력하신금액이맞습니까.mov
  public/assets/avatar/출금하실계좌를선택해주세요.mov
  src/stories/pages/depositPage/page2.jsx
  src/stories/pages/loanPage/page2.jsx
  src/stories/pages/transferPage/index.js
  src/stories/pages/transferPage/page2.js
Labels: ✨feat

#255 [feat] 전체 상품 목록 페이지 버그 수정
  src/stories/molecules/searchBar/index.js
  src/stories/pages/productPage/index.jsx
Labels: 🐛bug

#256 [fix] 개인정보 주거래 계좌 목록 토글로 변경
  src/stories/pages/fixMyPage/index.js
  src/stories/pages/myPage/index.js
Labels: 🐛bug

#258 [fix] 페이지 이동시 result value 초기화
  src/stories/pages/transferPage/index.js
Labels: 🐛bug

#259 [docs] 불필요한 파일 삭제
  public/assets/avatar/계좌비밀번4자리를말씀해주세요.mov
  public/assets/avatar/계좌비밀번호를다시한번입력해주세요.mov
  public/assets/avatar/계좌비밀번호숫4자리를설정해주세요.mov
  public/assets/avatar/계좌생성이완료되었습니다.mov
  public/assets/avatar/계좌이체를취소합니 .mov
  public/assets/avatar/다음화면으로이동합니.mov
  public/assets/avatar/상품가입을진행합니다.mov
  public/assets/avatar/상품가입페이지로이동합니다.mov
  public/assets/avatar/상품가입화면으로이동합니다.mov
  public/assets/avatar/상품상세페이지로이동합니다.mov
  public/assets/avatar/상품페이지로이동합니다.mov
  public/assets/avatar/어떤계좌로돈을보낼까요.mov
  public/assets/avatar/어떤상품을찾으시나요.mov
  public/assets/avatar/얼마를보낼까요.mov
  public/assets/avatar/얼마를저축할까요최소납입금액3만원입니다.mov
  public/assets/avatar/이체하시겠습니까.mov
  public/assets/avatar/이체화면으로이동합니다.mov
  public/assets/avatar/입력하신계좌번호가맞습니까.mov
  public/assets/avatar/입력하신금액이맞습니까.mov
  public/assets/avatar/출금하실계좌를선택해주세요.mov
Labels: 📄 docs

#262 [feat] 금융상식톡톡 - 방카슈랑스 정보성 페이지
  public/assets/bancassurance.gif
  src/routes/noLayoutRouter.js
  src/stories/molecules/mainCarousel/index.js
  src/stories/pages/InfoPage/bancassurancePage.jsx
  src/stories/pages/mainPage/index.jsx
  src/stories/pages/myPage/index.js
  src/styles/animations.css
Labels: ✨feat, 🎨ui

#264 [feat] [feat] 금융상식톡톡 - 신용대출 전 유의사항 정보성 페이지
  src/routes/noLayoutRouter.js
  src/stories/pages/InfoPage/bancassurancePage.jsx
  src/stories/pages/InfoPage/precautionPage.jsx
  src/stories/pages/mainPage/index.jsx
  tailwind.config.js
Labels: ✨feat, 🎨ui

#275 [feat] 계좌 이체 음성인식 ai 통신
  src/stories/pages/bottomPages/transferCheckPage/index.js
  src/stories/pages/depositPage/index.jsx
  src/stories/pages/depositPage/page2.jsx
  src/stories/pages/transferPage/index.js
  src/stories/pages/transferPage/page1.js
  src/stories/pages/transferPage/page2.js
Labels: ✨feat

#277 [design] ai 음성 캐릭터 사이즈 조정
  src/App.js
  src/stories/organisms/videoComp/index.js
  src/stories/organisms/voiceServiceComp/index.jsx
Labels: 🎨ui

#278 [feat] 영상 자동 재생 토글 버튼
  src/App.js
  src/stories/organisms/autoPlayToggle/index.js
  src/stories/organisms/videoComp/index.js
  src/stories/pages/transferAccountPage/index.js
Labels: ✨feat

#279 [fix] 영상 자동 재생 토글 버튼 기본값 setting 기능
  src/App.js
  src/stories/organisms/autoPlayToggle/index.js
  src/stories/organisms/videoComp/index.js
Labels: 🐛bug
